{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vesting-backend.fullname" . }}
  labels:
    {{- include "vesting-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ include "vesting-backend.fullname" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.keys }}
    - secretKey: {{ .localKey }}
      remoteRef:
        key: {{ $.Values.externalSecret.remoteSecretKey }}
        property: {{ .remoteProperty }}
    {{- end }}
{{- end }}
